(function(){
  let signedRecord=null;
  async function encodeFiles(files){return Promise.all([...files].map(async f=>({name:f.name,type:f.type,data:await fileAsBase64(f)})))}
  window.openSignedUpload=function(record){signedRecord=record;$('#signedUploadName').textContent=record.meeting_name+' · '+record.created_at.replace('T',' ');$('#signedEditableFiles').value='';$('#signedScannedFiles').value='';$('#signedUploadDialog').showModal()};
  $('#submitSignedUpload').onclick=async()=>{const button=$('#submitSignedUpload'),editable=$('#signedEditableFiles').files,scanned=$('#signedScannedFiles').files;if(!editable.length&&!scanned.length){alert('请至少选择一份可编辑版本或定稿扫描件');return}button.disabled=true;button.textContent='正在保存…';try{const response=await fetch('/api/upload-signed-files',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({record_id:signedRecord.id,editable:await encodeFiles(editable),scanned:await encodeFiles(scanned)})}),result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'上传失败');$('#signedUploadDialog').close();await loadRecords()}catch(err){alert(err.message)}finally{button.disabled=false;button.textContent='上传并保存'}};
  function updateHistoryOptions(){const type=$('#historyMeetingType').value,select=$('#historyMeetingNo');select.innerHTML='';const max=type==='board'?15:type==='supervisory'?5:0;if(!max){select.innerHTML='<option value="">股东会历史目录暂空</option>';return}for(let i=1;i<=max;i++){const o=document.createElement('option');o.value=i;o.textContent=`第一届${type==='board'?'董事会':'监事会'}第${recordCnNum(i)}次会议`;select.append(o)}}
  function openHistoryUpload(record=null){const type=record?.meeting_type||'board';$('#historyMeetingType').value=type;updateHistoryOptions();$('#historyMeetingNo').value=record?.input?.meeting_no||1;$('#historyMeetingType').disabled=!!record;$('#historyMeetingNo').disabled=!!record;$('#historyEditableFiles').value='';$('#historyScannedFiles').value='';$('#historyUploadMode').value='append';$('#historyUploadName').textContent=record?`修改：${record.meeting_name}`:'';$('#historyUploadDialog').showModal()}
  window.openHistoryUpload=openHistoryUpload;
  $('#openHistoryUpload').onclick=()=>openHistoryUpload();$('#historyMeetingType').onchange=updateHistoryOptions;
  $('#submitHistoryUpload').onclick=async()=>{const type=$('#historyMeetingType').value,no=$('#historyMeetingNo').value,editable=$('#historyEditableFiles').files,scanned=$('#historyScannedFiles').files;if(type==='shareholder'){alert('股东会历史会议目录暂未配置');return}if(!editable.length&&!scanned.length){alert('请至少选择一份可编辑版本或签署版扫描件');return}const button=$('#submitHistoryUpload');button.disabled=true;button.textContent='正在归档…';try{const response=await fetch('/api/upload-history',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({meeting_type:type,meeting_no:+no,mode:$('#historyUploadMode').value,editable:await encodeFiles(editable),scanned:await encodeFiles(scanned)})}),result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'上传失败');$('#historyUploadDialog').close();await loadRecords()}catch(err){alert(err.message)}finally{button.disabled=false;button.textContent='上传并归档'}};
})();
