(function(){
  let signedRecord=null;
  const docLabels=['会议议案','会议通知','通知回执','签到表','会议议程','表决票','会议记录','会议决议','计票情况'];
  async function encodeFiles(files){return Promise.all([...files].map(async f=>({name:f.name,type:f.type,data:await fileAsBase64(f)})))}
  function renderSignatureInputs(record){
    const box=$('#signaturePageInputs');
    const labels=docLabels.filter(label=>(record.files||[]).some(name=>String(name).includes(label)));
    box.innerHTML=labels.map(label=>`<label class="signature-page-row"><span>${esc(label)}</span><input type="file" class="signature-page-file" data-label="${esc(label)}" multiple accept=".pdf,.png,.jpg,.jpeg,.webp,.bmp,image/*"></label>`).join('');
  }
  window.openSignedUpload=function(record){signedRecord=record;$('#signedUploadName').textContent=record.meeting_name+' · '+record.created_at.replace('T',' ');$('#signedEditableFiles').value='';$('#signedScannedFiles').value='';renderSignatureInputs(record);$('#signedUploadDialog').showModal()};
  $('#submitSignedUpload').onclick=async()=>{const button=$('#submitSignedUpload'),editable=$('#signedEditableFiles').files,scanned=$('#signedScannedFiles').files,signatureRows=$$('.signature-page-file');const signature_pages={};for(const input of signatureRows){if(input.files.length)signature_pages[input.dataset.label]=await encodeFiles(input.files)}const hasSignature=Object.keys(signature_pages).length>0;if(!editable.length&&!scanned.length&&!hasSignature){alert('请至少选择一份可编辑版本、定稿扫描件或签字页扫描件');return}button.disabled=true;button.textContent='正在保存…';try{const response=await fetch('/api/upload-signed-files',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({record_id:signedRecord.id,editable:await encodeFiles(editable),scanned:await encodeFiles(scanned),signature_pages})}),result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'上传失败');$('#signedUploadDialog').close();await loadRecords();if(result.complete_pdfs&&Object.keys(result.complete_pdfs).length)alert('已生成完整签署版PDF')}catch(err){alert(err.message)}finally{button.disabled=false;button.textContent='上传并保存'}};
  function updateHistoryOptions(){const disabled=$('#historyMeetingType').value==='shareholder';$('#historyTermNo').disabled=disabled;$('#historyMeetingNo').disabled=disabled}
  function openHistoryUpload(record=null){const type=record?.meeting_type||'board',uploads=record?.history_uploads;$('#historyMeetingType').value=type;updateHistoryOptions();$('#historyTermNo').value=record?.input?.term_no||1;$('#historyMeetingNo').value=record?.input?.meeting_no||1;$('#historyMeetingType').disabled=!!record;$('#historyTermNo').disabled=!!record||type==='shareholder';$('#historyMeetingNo').disabled=!!record||type==='shareholder';$('#historyEditableFiles').value='';$('#historyScannedFiles').value='';$('#historyUploadMode').value='append';$('#historyUploadName').textContent=record?`修改：${record.meeting_name}`:'';$('#historyExistingSummary').textContent=record?(uploads?`现有：可编辑版本 ${uploads.editable?.length||0} 份；签署版扫描件 ${uploads.scanned?.length||0} 份。`:`现有 ${record.files?.length||0} 份旧版未分类文件，请选择“替换”并按类别重新上传。`):'';$('#historyUploadDialog').showModal()}
  window.openHistoryUpload=openHistoryUpload;
  $('#openHistoryUpload').onclick=()=>openHistoryUpload();$('#historyMeetingType').onchange=updateHistoryOptions;
  $('#submitHistoryUpload').onclick=async()=>{const type=$('#historyMeetingType').value,term=$('#historyTermNo').value,no=$('#historyMeetingNo').value,editable=$('#historyEditableFiles').files,scanned=$('#historyScannedFiles').files;if(type==='shareholder'){alert('股东会历史会议目录暂未配置');return}if(!editable.length&&!scanned.length){alert('请至少选择一份可编辑版本或签署版扫描件');return}const button=$('#submitHistoryUpload');button.disabled=true;button.textContent='正在归档…';try{const response=await fetch('/api/upload-history',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({meeting_type:type,term_no:+term,meeting_no:+no,mode:$('#historyUploadMode').value,editable:await encodeFiles(editable),scanned:await encodeFiles(scanned)})}),result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'上传失败');$('#historyUploadDialog').close();await loadRecords()}catch(err){alert(err.message)}finally{button.disabled=false;button.textContent='上传并归档'}};
})();
