function recordCnNum(value){
  const n=+value,d='零一二三四五六七八九';
  if(n<10)return d[n]||String(value);if(n<20)return '十'+(n%10?d[n%10]:'');
  if(n<100)return d[Math.floor(n/10)]+'十'+(n%10?d[n%10]:'');return String(value)
}
function recordHierarchy(record){
  const input=record.input||{},type=record.meeting_type;
  if(type==='shareholder'){const year=+(input.meeting_year||0),annual=input.shareholder_kind==='annual';return {typeOrder:0,typeLabel:'股东会',termNo:year,meetingNo:annual?0:+(input.meeting_no||0),term:`${year}年`,meeting:annual?'年度股东会会议':`第${recordCnNum(input.meeting_no||1)}次临时股东会会议`}}
  if(type==='board')return {typeOrder:1,typeLabel:'董事会',termNo:+(input.term_no||0),meetingNo:+(input.meeting_no||0),term:`第${recordCnNum(input.term_no||1)}届`,meeting:`第${recordCnNum(input.meeting_no||1)}次会议`};
  return {typeOrder:2,typeLabel:'监事会',termNo:+(input.term_no||0),meetingNo:+(input.meeting_no||0),term:`第${recordCnNum(input.term_no||1)}届`,meeting:`第${recordCnNum(input.meeting_no||1)}次会议`}
}
function recordStatusText(r){const base=r.status==='notice_final'?'通知定稿 '+(r.final_notice_date||''):r.status==='signed_final'?'签署定稿':r.status==='draft'?'未定稿':'待确认',uploads=r.historical?r.history_uploads:r.signed_uploads,signatureCount=Object.values(r.signature_pages||{}).reduce((sum,items)=>sum+(items?.length||0),0),pdfCount=Object.keys(r.complete_signed_pdfs||{}).length,extra=uploads?` · 可编辑版本 ${uploads.editable?.length||0}份 · 签署版扫描件 ${uploads.scanned?.length||0}份`:r.historical?` · 未分类历史文件 ${r.files?.length||0}份`:'';return base+extra+(signatureCount?` · 签字页 ${signatureCount}份`:'')+(pdfCount?` · 完整PDF ${pdfCount}份`:'')}
function completePdfLinks(r){const pdfs=r.complete_signed_pdfs||{},labels=Object.keys(pdfs);if(!labels.length)return '';return `<div class="record-pdf-links">${labels.map(label=>`<a href="/api/archive-files/${encodeURIComponent(r.id)}/${encodeURIComponent(pdfs[label])}">${esc(label)}PDF</a>`).join('')}</div>`}
async function deleteRecord(record){const final=record.status==='notice_final'||record.status==='signed_final',warning=final?'该记录属于定稿版，删除后其输出文件及归档副本均无法恢复。':'删除后该记录及对应的Word文件均无法恢复。';if(!confirm(`${warning}\n\n确定删除“${record.meeting_name}”于 ${record.created_at.replace('T',' ')} 生成的记录吗？`))return;const response=await fetch('/api/delete-record',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({record_id:record.id})}),result=await response.json();if(!response.ok||!result.ok){alert(result.error||'删除失败');return}await loadRecords()}
function confirmRecord(record){const dlg=$('#archiveDialog'),status=$('#archiveStatus'),dateWrap=$('#finalNoticeDateWrap'),date=$('#finalNoticeDate');dlg.querySelector('h2').textContent='确认生成记录';$('#previousName').textContent=record.meeting_name+' · '+record.created_at.replace('T',' ');dlg.querySelector('button[value="confirm"]').textContent='确认';status.value=['draft','notice_final','signed_final'].includes(record.status)?record.status:'draft';date.value=record.final_notice_date||'';dateWrap.classList.toggle('hidden',status.value!=='notice_final');dlg.returnValue='';dlg.onclose=async()=>{if(dlg.returnValue!=='confirm')return;if(status.value==='notice_final'&&!date.value){alert('请填写通知用定稿版的具体通知日期');setTimeout(()=>dlg.showModal(),0);return}const response=await fetch('/api/archive',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({record_id:record.id,status:status.value,notice_date:date.value})}),result=await response.json();if(!response.ok||!result.ok){alert(result.error||'确认失败');return}await loadRecords()};dlg.showModal()}
loadRecords=async function(){
  records=await fetch('/api/records').then(r=>r.json());const box=$('#recordList');box.innerHTML='';
  if(!records.length){box.innerHTML='<p>尚无记录</p>';return}
  const types=new Map();
  records.forEach(r=>{const h=recordHierarchy(r),typeKey=h.typeLabel;if(!types.has(typeKey))types.set(typeKey,{...h,terms:new Map()});const type=types.get(typeKey),termKey=h.termNo;if(!type.terms.has(termKey))type.terms.set(termKey,{...h,meetings:new Map()});const term=type.terms.get(termKey);if(!term.meetings.has(h.meetingNo))term.meetings.set(h.meetingNo,{label:h.meeting,items:[]});term.meetings.get(h.meetingNo).items.push(r)});
  [...types.values()].sort((a,b)=>a.typeOrder-b.typeOrder).forEach(type=>{
    const typeNode=document.createElement('details');typeNode.className='record-type';typeNode.open=true;typeNode.innerHTML=`<summary>${esc(type.typeLabel)}</summary><div class="record-type-body"></div>`;const typeBody=typeNode.lastElementChild;
    [...type.terms.values()].sort((a,b)=>a.termNo-b.termNo).forEach(term=>{
      const termNode=document.createElement('details');termNode.className='record-term';termNode.open=true;termNode.innerHTML=`<summary>${esc(term.term)}</summary><div class="record-term-body"></div>`;const termBody=termNode.lastElementChild;
      [...term.meetings.entries()].sort((a,b)=>a[0]-b[0]).forEach(([,meeting])=>{const meetingNode=document.createElement('details');meetingNode.className='record-meeting';meetingNode.open=true;meetingNode.innerHTML=`<summary>${esc(meeting.label)}</summary><div class="record-time-list"></div>`;const list=meetingNode.lastElementChild;meeting.items.sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)).forEach(r=>{const row=document.createElement('div');row.className='record-row '+(r.status.includes('final')?'final-record':'');const normalActions=r.historical?`<button type="button" class="secondary history-edit">${r.history_uploads?'修改文件':'重新分类'}</button>`:`<button type="button" class="secondary recall-record">调取</button><button type="button" class="secondary confirm-record">确认</button>${r.status==='signed_final'?'<button type="button" class="secondary signed-upload">上传签署版本</button>':''}`;row.innerHTML=`<div><small>${r.created_at.replace('T',' ')}</small><em>${recordStatusText(r)}</em>${completePdfLinks(r)}</div><div class="record-actions">${normalActions}<button type="button" class="danger delete-record">删除</button></div>`;row.querySelector('.recall-record')?.addEventListener('click',()=>fill(r.input));row.querySelector('.confirm-record')?.addEventListener('click',()=>confirmRecord(r));row.querySelector('.signed-upload')?.addEventListener('click',()=>openSignedUpload(r));row.querySelector('.history-edit')?.addEventListener('click',()=>openHistoryUpload(r));row.querySelector('.delete-record').onclick=()=>deleteRecord(r);list.append(row)});termBody.append(meetingNode)});typeBody.append(termNode)
    });box.append(typeNode)
  })
};
loadRecords();
